server:
    port: ${PORT:8080}
    servlet:
        context-path: "/api"

spring:
    profiles:
        active: local
    application:
        name: "SterioX"
    datasource:
        url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5432/sterio_x}
        driverClassName: org.postgresql.Driver
        password: ${DBMS_PASSWORD:root}
        username: ${DBMS_USERNAME:root}
    jpa:
        hibernate:
            ddl-auto: update
            
jwt:
    secret-key: ${JWT_SECRET_KEY:local-dev-secret-key-32bytes!!!}
    valid-duration: ${JWT_EXPIRATION_S:3600}
    refreshable-duration: ${JWT_REFRESHABLE_S:86400}

