version: '3.8'

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: nginx-rtmp-server
    ports:
      - "1935:1935"
      - "5555:80" 
    volumes:
      # CHỈ CẦN MOUNT 1 FILE DUY NHẤT NÀY
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - media-network

networks:
  media-network:
    driver: bridge